name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - QAT
          - UAT
          - QAT_ADMIN
          - UAT_ADMIN

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    env:
      APP_ENV: ${{ github.event.inputs.environment }}

      QAT_URL: ${{ secrets.QAT_URL }}
      QAT_USERNAME_1: ${{ secrets.QAT_USERNAME_1 }}
      QAT_PASSWORD_1: ${{ secrets.QAT_PASSWORD_1 }}

      UAT_URL: ${{ secrets.UAT_URL }}
      UAT_USERNAME_1: ${{ secrets.UAT_USERNAME_1 }}
      UAT_PASSWORD_1: ${{ secrets.UAT_PASSWORD_1 }}

      QAT_ADMIN_URL: ${{ secrets.QAT_ADMIN_URL }}
      QAT_ADMIN_USERNAME: ${{ secrets.QAT_ADMIN_USERNAME }}
      QAT_ADMIN_PASSWORD: ${{ secrets.QAT_ADMIN_PASSWORD }}

      UAT_ADMIN_URL: ${{ secrets.UAT_ADMIN_URL }}
      UAT_ADMIN_USERNAME: ${{ secrets.UAT_ADMIN_USERNAME }}
      UAT_ADMIN_PASSWORD: ${{ secrets.UAT_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report